### PR TITLE
[E] Extend Functionality

### LINKED ISSUE #20: Fix flakey process test
```go
{
	name: "multiple URLs",
	args: args{
		urls: []string{server.URL + "/text", server.URL + "/html"},
	},
	want: []common.Chunk{
		{Content: "A plain text file.", Source: server.URL + "/text"},
		{Content: "An HTML file.", Source: server.URL + "/html"},
	},
	wantErr: false,
},
```

test fails on the returned order
it can be text/html or html/text

### PR DESCRIPTION
**Pull request by mmatongo**
closes #20

### CODE REVIEW

**Comment by mmatongo** [comment]
@ccoVeille thoughts? there's a bit of gibberish in there

File: chew.go [hunk 1]
```diff
@@ -186,7 +391,25 @@ func processURL(url string, ctxs ...context.Context) ([]common.Chunk, error) {
...
+		if proxyURL := getNextProxy(); proxyURL != nil {
+			transport = &http.Transport{
+				Proxy: http.ProxyURL(proxyURL),
+			}
+		}
+		client = &http.Client{
+			Timeout:   30 * time.Second,
+			Transport: transport,
+		}
+	}
```
Comment (ccoVeille) [inline chew.go]: What about this


```suggestion
	client := httpClient
	if client == nil {
		transport := http.DefaultTransport
		if proxyURL := getNextProxy(); proxyURL != nil {
			transport = &http.Transport{
				Proxy: http.ProxyURL(proxyURL),
			}
		}
		client = &http.Client{
			Timeout:   30 * time.Second,
			Transport: transport,
		}
	}
```

File: chew.go [hunk 2]
```diff
@@ -1,18 +1,54 @@
...
 	"sync"
+	"time"
 
 	"github.com/mmatongo/chew/v1/internal/common"
 	"github.com/mmatongo/chew/v1/internal/document"
 	"github.com/mmatongo/chew/v1/internal/text"
 	"github.com/mmatongo/chew/v1/internal/transcribe"
 	"github.com/mmatongo/chew/v1/internal/utils"
+	"github.com/temoto/robotstxt"
+	"golang.org/x/time/rate"
```
Comment (ccoVeille) [inline chew.go:53]: Usually external libraries are added in a dedicated section


```suggestion
 	"context"
 	"fmt"
 	"io"
 	"net/http"
	"net/url"
 	"strings"
 	"sync"
	"time"

	"github.com/temoto/robotstxt"
	"golang.org/x/time/rate"
 
 	"github.com/mmatongo/chew/v1/internal/common"
 	"github.com/mmatongo/chew/v1/internal/document"
 	"github.com/mmatongo/chew/v1/internal/text"
 	"github.com/mmatongo/chew/v1/internal/transcribe"
 	"github.com/mmatongo/chew/v1/internal/utils"
```

File: chew.go [hunk 3]
```diff
@@ -41,17 +77,126 @@ var contentTypeProcessors = map[string]func(io.Reader, string) ([]common.Chunk,
 	contentTypeEPUB:     document.ProcessEpub,
 }
 
+var (
+	rateLimiter       *rate.Limiter
+	robotsCache       = make(map[string]*robotstxt.RobotsData)
+	robotsMu          sync.RWMutex
+	userAgent         = "Chew/1.0 (+https://github.com/mmatongo/chew)"
```
Comment (ccoVeille) [inline chew.go]: This one could be a constant

File: chew.go [hunk 4]
```diff
@@ -41,17 +77,126 @@ var contentTypeProcessors = map[string]func(io.Reader, string) ([]common.Chunk,
...
+		UserAgent:       userAgent,
+		RetryLimit:      3,
+		RetryDelay:      5 * time.Second,
+		CrawlDelay:      10 * time.Second,
+		ProxyList:       []string{},
+		RateLimit:       rate.Every(2 * time.Second),
+		RateBurst:       3,
+		IgnoreRobotsTxt: false,
+	})
+}
```
Comment (ccoVeille) [inline chew.go]: I'm not fan of these:
- having a init
- having package variables

It could lead to race issues

I will try to develop if you are interested, but it would require a refactoring of the code in this PR

File: chew.go [hunk 5]
```diff
@@ -201,3 +424,102 @@ func processURL(url string, ctxs ...context.Context) ([]common.Chunk, error) {
...
+		}
+
+		robotsMu.Lock()
+		robotsCache[robotsURL] = robotsData
+		robotsMu.Unlock()
+	}
+
+	allowed := robotsData.TestAgent(parsedURL.Path, userAgent)
+
+	return allowed, crawlDelay, nil
```
Comment (ccoVeille) [inline chew.go]: I would remove the allowed from signature, and return an error when not allowed

File: chew.go [hunk 6]
```diff
@@ -119,7 +299,28 @@ func Process(urls []string, ctxs ...context.Context) ([]common.Chunk, error) {
...
+					allowed, crawlDelay, err := getRobotsTxtInfo(url)
+					if err != nil {
+						errCh <- fmt.Errorf("checking robots.txt for %s: %w", url, err)
+						return
+					}
+					if !allowed {
+						errCh <- fmt.Errorf("access to %s is disallowed by robots.txt", url)
+						return
+					}
+					if err := respectCrawlDelay(url, crawlDelay); err != nil {
```
Comment (ccoVeille) [inline chew.go]: You should pass the context as first argument

So you can cancel the time.Sleep when the context expires

File: chew.go [hunk 7]
```diff
@@ -96,6 +263,19 @@ Process takes a list of URLs and returns a list of Chunks
...
+	if err != nil {
+		log.Fatalf("Error processing URLs: %v", err)
+	}
+
+	for _, chunk := range chunks {
+		log.Printf("Chunk: %s\n Source: %s\n", chunk.Content, chunk.Source)
+	}
 */
 func Process(urls []string, ctxs ...context.Context) ([]common.Chunk, error) {
 	ctx := context.Background()
```
Comment (ccoVeille) [inline chew.go]: You should pass the context the first argument of the function

File: chew.go [hunk 8]
```diff
@@ -41,17 +77,126 @@ var contentTypeProcessors = map[string]func(io.Reader, string) ([]common.Chunk,
...
+manages the transcription process, and returns the resulting transcript.
+
+For detailed usage instructions, see the TranscribeOptions struct documentation.
 */
 var Transcribe = transcribe.Transcribe
 
+/*
+The TranscribeOptions struct contains the options for transcribing an audio file. It allows the user
+to specify the Google Cloud credentials, the GCS bucket to upload the audio file to, the language code
+to use for transcription, a potion to enable diarization including the min and max speakers and
```
Comment (ccoVeille) [inline chew.go]: maybe something to explain what is diarization

```suggestion
to use for transcription, a potion to enable diarization (blah blah...) including the min and max speakers and
```

File: chew.go (hunk 7 above)
Comment (ccoVeille) [reply chew.go]: But I'm noticing you have a big issue with the way you handle your context

it should be addressed, but not necessarily in this PR

File: chew.go [hunk 9]
```diff
@@ -201,3 +424,102 @@ func processURL(url string, ctxs ...context.Context) ([]common.Chunk, error) {
...
+
+	lastAccessMu.Lock()
+	defer lastAccessMu.Unlock()
+
+	lastAccess, exists := lastAccessTimes[domain]
+	if exists {
+		timeToWait := time.Until(lastAccess.Add(delay))
+		if timeToWait > 0 {
+			time.Sleep(timeToWait)
+		}
```
Comment (ccoVeille) [inline chew.go]: a time.Sleep is blocking

if you have a context that expires (when the app dies for example), the sleep cannot be cancelled

I would like to suggest you adding a function to sleep

```go
func Wait(ctx, d time.Duration) {
      select {
          case <-time.After(d):         
          case <-ctx.Done():
}
````

This way you don't wait when the context is expired

File: chew.go [hunk 10]
```diff
@@ -201,3 +424,102 @@ func processURL(url string, ctxs ...context.Context) ([]common.Chunk, error) {
...
+	}
+
+	lastAccessTimes[domain] = time.Now()
+	return nil
+}
+
+func processWithRetry(url string, ctx context.Context) ([]common.Chunk, error) {
```
Comment (ccoVeille) [inline chew.go]:
```suggestion
func processWithRetry(ctx context.Context, url string) ([]common.Chunk, error) {
```

the context is by convention always the first argument, the same way the error is always the last one

File: chew.go [hunk 11]
```diff
@@ -148,6 +349,10 @@ func Process(urls []string, ctxs ...context.Context) ([]common.Chunk, error) {
 	return result, nil
 }
 
+/*
+processURL handles the actual processing of a single URL or file
+file paths are processed directly while URLs are fetched and processed
+*/
 func processURL(url string, ctxs ...context.Context) ([]common.Chunk, error) {
```
Comment (ccoVeille) [inline chew.go]: it's an internal function, you should refactor it

ctxs as a variadic is not a good thing

You should have this

```suggestion
func processURL(ctx context.Context, url string) ([]common.Chunk, error) {
```

File: chew.go [hunk 12]
```diff
@@ -201,3 +424,102 @@ func processURL(url string, ctxs ...context.Context) ([]common.Chunk, error) {
...
+	/*
+		This bit of code makes a lot of very unhealthy assumptions, in an ideal world this
+		would be more straightforward but unfortunately it's not.
+
+		Use this with caution and respect for site owners.
+	*/
+	if !exists {
+		resp, err := http.Get(robotsURL)
+		if err != nil {
+			return true, crawlDelay, nil
```
Comment (ccoVeille) [inline chew.go]: returning a crawl delay via this function while  crawlDelay is a global variable is a bad idea

I mean this function don't handle/alter the crawlDelay, you should simply use it where you call this function

File: chew.go [hunk 13]
```diff
@@ -201,3 +424,102 @@ func processURL(url string, ctxs ...context.Context) ([]common.Chunk, error) {
...
+	)
+
+	for i := 0; i < retryLimit; i++ {
+		chunks, err = processURL(url, ctx)
+		if err == nil {
+			return chunks, nil
+		}
+
+		if i < retryLimit-1 {
+			time.Sleep(retryDelay)
```
Comment (ccoVeille) [inline chew.go]: same remark as before this time.Sleep should check the context

File: chew.go [hunk 14]
```diff
@@ -67,6 +212,28 @@ var validExtensions = map[string]func(io.Reader, string) ([]common.Chunk, error)
...
+
+	client := &http.Client{
+		Transport: loggingRoundTripper{wrapped: http.DefaultTransport},
+	}
+
+	chew.SetHTTPClient(client)
+*/
+func SetHTTPClient(client *http.Client) {
+	httpClient = client
+}
```
Comment (ccoVeille) [inline chew.go]: This should be something that is not at package level, but a method of an object

Your NewConfig object is a good idea, but you should have a Chew instance returned, then SettHTTPClient can be used on it

All your existing methods should be replaced to me method of the object

Then if you want to keep a retro compatibility, you should create a defaultChew = NewChewig(common.Config{})

then you rewrite existing exported method to call the defaultChew

```go
func Process(urls []string, ctxs ...context.Context) ([]common.Chunk, error) {
	ctx := context.Background()
	if len(ctxs) > 0 {
		ctx = ctxs[0]
	}
	return defaultChew.Process(ctx, urls)
}
```

File: chew.go [hunk 15]
```diff
@@ -96,6 +263,19 @@ Process takes a list of URLs and returns a list of Chunks
...
+	chunks, err := chew.Process([]string{"https://example.com", "file://path/to/file.txt"})
+	if err != nil {
+		log.Fatalf("Error processing URLs: %v", err)
+	}
+
+	for _, chunk := range chunks {
+		log.Printf("Chunk: %s\n Source: %s\n", chunk.Content, chunk.Source)
+	}
 */
 func Process(urls []string, ctxs ...context.Context) ([]common.Chunk, error) {
```
Comment (ccoVeille) [inline chew.go]: it's too later but ctx should always be the first argument, here you used a variadic trick to solve the issues, but it's a bit dirty, especially if you consider the variadic can be used to pass more than one context, and your code will silently only use the first one

If it's not too late, I would change the signature

Comment (ccoVeille) [reply chew.go]: The number of your stars, and the fact there is no public project using chew for now, means it's not too late

https://pkg.go.dev/github.com/mmatongo/chew
> Imported by: 0

**Review by ccoVeille — CHANGES_REQUESTED** [review]

File: chew.go (hunk 7 above)
Comment (mmatongo) [reply chew.go]: I think I see what you mean

File: chew.go (hunk 11 above)
Comment (mmatongo) [reply chew.go]: I didn't actually know that this was the case, initially I made it like this so that the context itself would be optional

**Comment by mmatongo** [comment]
@ccoVeille let me address the issues raised and request another review, thank you for the insight. I really appreciate it

**Comment by ccoVeille** [comment]
Sure! Good luck and have fun! 😁

File: chew.go [hunk 16]
```diff
@@ -1,18 +1,54 @@
+/*
+Package chew provides a simple way to process URLs and files. It allows you to process a list of URLs
+and files and returns the content of the URLs and files as a list of Chunks. It also provides a way to
```
Comment (ccoVeille) [inline chew.go]:
```suggestion
and files, and returns the content of the URLs and files as a list of Chunks. It also provides a way to
```

File: chew.go [hunk 17]
```diff
@@ -1,18 +1,54 @@
...
+transcribe audio files using the Google Cloud Speech-to-Text API or the OpenAI Whisper API.
+
+The library respects robots.txt files and crawl delays, and allows you to set a custom http.Client for making requests.
+
+Note on Responsible Usage:
+
+This library is designed for processing data from both local files and web sources. Users should be aware of the following considerations:
+
+1. Web Scraping:
+  - When scraping websites, ensure compliance with the target website's terms of service and robots.txt rules.
```
Comment (ccoVeille) [inline chew.go:13]: You should add something about the fact even if the library tries to respect the robots.txt file, the user is responsible.

Or something like that

File: chew.go (hunk 16 above)
Comment (ccoVeille) [inline chew.go]:
```suggestion
and files and returns the content of the URLs and files as a list of chunks. It also provides a way to
```

File: chew.go [hunk 18]
```diff
@@ -1,18 +1,54 @@
+/*
+Package chew provides a simple way to process URLs and files. It allows you to process a list of URLs
+and files and returns the content of the URLs and files as a list of Chunks. It also provides a way to
+transcribe audio files using the Google Cloud Speech-to-Text API or the OpenAI Whisper API.
+
+The library respects robots.txt files and crawl delays, and allows you to set a custom http.Client for making requests.
```
Comment (ccoVeille) [inline chew.go]:
```suggestion
The library respects rules defined in robots.txt file and crawl delays, and allows you to set a custom http.Client for making requests.
```

There is only one robots.txt file unless I'm wrong

File: chew.go (hunk 2 above)
Comment (ccoVeille) [reply chew.go:53]: You didn't work on this

File: chew.go [hunk 19]
```diff
@@ -41,17 +77,122 @@ var contentTypeProcessors = map[string]func(io.Reader, string) ([]common.Chunk,
...
+manages the transcription process, and returns the resulting transcript.
+
+For detailed usage instructions, see the TranscribeOptions struct documentation.
 */
 var Transcribe = transcribe.Transcribe
 
+/*
+The TranscribeOptions struct contains the options for transcribing an audio file. It allows the user
+to specify the Google Cloud credentials, the GCS bucket to upload the audio file to, the language code
+to use for transcription, a potion to enable diarization (the process of separating and labeling
```
Comment (ccoVeille) [inline chew.go]: Is potion the right word?

File: chew.go [hunk 20]
```diff
@@ -41,17 +77,122 @@ var contentTypeProcessors = map[string]func(io.Reader, string) ([]common.Chunk,
...
+speakers in an audio stream) including the min and max speakers and
+an option to clean up the audio file from GCS after transcription is complete.
```
Comment (ccoVeille) [inline chew.go]: Please write something like this


```suggestion
an option to clean up the audio file from Google Cloud Speech-to-Text (GCS) after transcription is complete.
```

File: chew.go [hunk 21]
```diff
@@ -201,3 +397,112 @@ func processURL(url string, ctxs ...context.Context) ([]common.Chunk, error) {
...
+		timeToWait := time.Until(lastAccess.Add(delay))
+		if timeToWait > 0 {
+			c.lastAccessMu.Unlock()
+			timer := time.NewTimer(timeToWait)
+			select {
+			case <-timer.C:
+			case <-ctx.Done():
+				timer.Stop()
+				return ctx.Err()
+			}
```
Comment (ccoVeille) [inline chew.go]: Here is a simpler way.

```suggestion
			select {
			case <-timer.After(timeToWait):
			case <-ctx.Done():
				return ctx.Err()
			}
```

Comment (ccoVeille) [inline chew.go]: If you don't use my suggestion of using time.After 

Then you should consider using defer timer.Stop


```suggestion
			timer := time.NewTimer(timeToWait)
			defer timer.Stop()
			select {
			case <-timer.C:
			case <-ctx.Done():
				return ctx.Err()
			}
```

File: chew.go [hunk 22]
```diff
@@ -201,3 +397,112 @@ func processURL(url string, ctxs ...context.Context) ([]common.Chunk, error) {
...
+		if err == nil {
+			return chunks, nil
+		}
+
+		if i < c.config.RetryLimit-1 {
+			c.wait(ctx, c.config.RetryDelay)
+		}
+	}
+
+	return nil, err
```
Comment (ccoVeille) [inline chew.go]:
```suggestion
	var retries int
	for {
		chunks, err = c.processURL(ctx, url)
		if err == nil {
			return chunks, nil
		}

		if retries > c.config.RetryLimit {
			break
		}
		retries++
		c.wait(ctx, c.config.RetryDelay)
	}

	return nil, err
```

File: chew.go (hunk 17 above)
Comment (mmatongo) [reply chew.go:13]: Okay

File: chew.go (hunk 19 above)
Comment (mmatongo) [reply chew.go]: Nope, should be an option

File: chew.go (hunk 20 above)
Comment (mmatongo) [reply chew.go]: done

File: chew.go (hunk 21 above)
Comment (mmatongo) [reply chew.go]: I used your earlier suggestion and it exposed a race condition. Thanks!!!

File: chew.go (hunk 19 above)
Comment (ccoVeille) [reply chew.go]: Haha 😂

File: chew.go (hunk 21 above)
Comment (ccoVeille) [reply chew.go]: Great then
